"""
PostHog Engineer Impact Dashboard
===================================
Run locally:
    pip install streamlit pandas plotly
    streamlit run dashboard.py

Deploy:
    Push both dashboard.py + posthog_data.json to a GitHub repo,
    then connect it to Streamlit Community Cloud at share.streamlit.io.

Data source:
    posthog_data.json  (generated by fetch_posthog_data.py)
    If the file is absent, the app loads a realistic built-in sample dataset
    so you can preview the UI immediately.
"""

import json
from datetime import datetime
from pathlib import Path
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="PostHog · Engineer Impact",
    page_icon="🦔",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Design tokens & CSS ───────────────────────────────────────────────────────

POSTHOG_ORANGE = "#F54E00"
POSTHOG_CREAM  = "#FFFAF0"
DARK_BG        = "#0D0D0D"
CARD_BG        = "#161616"
BORDER         = "#2A2A2A"
MUTED          = "#6B6B6B"
TEXT           = "#F0EDE8"
ACCENT_BLUE    = "#3B82F6"
ACCENT_GREEN   = "#22C55E"
ACCENT_AMBER   = "#F59E0B"

def hex_to_rgba(hex_color: str, alpha: float) -> str:
    """Convert a 6-digit hex color + float alpha (0–1) to an rgba() string.

    Plotly color properties accept rgba() but NOT 8-digit hex (#RRGGBBAA).
    Always use this helper instead of string-concatenating opacity suffixes.

    Example:
        hex_to_rgba("#F54E00", 0.53)  →  "rgba(245, 78, 0, 0.53)"
    """
    hex_color = hex_color.lstrip("#")
    r, g, b = (int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {alpha})"


PLOTLY_TEMPLATE = dict(
    layout=dict(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(family="'DM Mono', monospace", color=TEXT, size=12),
        colorway=[POSTHOG_ORANGE, ACCENT_BLUE, ACCENT_GREEN, ACCENT_AMBER,
                  "#A78BFA", "#EC4899", "#06B6D4", "#84CC16"],
        xaxis=dict(gridcolor=BORDER, zerolinecolor=BORDER, tickfont=dict(size=11)),
        yaxis=dict(gridcolor=BORDER, zerolinecolor=BORDER, tickfont=dict(size=11)),
        hoverlabel=dict(bgcolor=CARD_BG, bordercolor=BORDER, font_color=TEXT),
        legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor=BORDER),
        margin=dict(l=16, r=16, t=32, b=16),
    )
)

st.markdown(f"""
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,400&family=Bricolage+Grotesque:wght@400;500;600;700;800&display=swap');

  html, body, [data-testid="stApp"] {{
    background-color: {DARK_BG};
    color: {TEXT};
    font-family: 'DM Mono', monospace;
  }}

  /* Hide Streamlit chrome — keep toolbar visible for the Deploy button */
  

  /* Page wrapper */
  .main .block-container {{
    padding: 2rem 2.5rem 4rem;
    max-width: 1400px;
  }}

  /* ── Header ── */
  .ph-header {{
    display: flex;
    align-items: center;
    gap: 1.25rem;
    margin-bottom: 0.25rem;
  }}
  .ph-logo {{
    font-size: 2.6rem;
    line-height: 1;
  }}
  .ph-title {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 2rem;
    font-weight: 800;
    color: {TEXT};
    margin: 0;
    letter-spacing: -0.03em;
  }}
  .ph-subtitle {{
    font-size: 0.78rem;
    color: {MUTED};
    margin: 0;
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }}
  .ph-badge {{
    display: inline-block;
    background: {POSTHOG_ORANGE};
    color: #fff;
    font-size: 0.65rem;
    font-weight: 500;
    padding: 0.18rem 0.55rem;
    border-radius: 999px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    vertical-align: middle;
    margin-left: 0.5rem;
  }}
  .divider {{
    height: 1px;
    background: linear-gradient(90deg, {POSTHOG_ORANGE}55 0%, {BORDER} 60%);
    margin: 1.5rem 0;
    border: none;
  }}

  /* ── Stat cards ── */
  .stat-grid {{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1rem;
    margin-bottom: 1.5rem;
  }}
  .stat-card {{
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 10px;
    padding: 1.1rem 1.3rem;
    position: relative;
    overflow: hidden;
  }}
  .stat-card::before {{
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
    background: linear-gradient(90deg, {POSTHOG_ORANGE}, transparent);
  }}
  .stat-label {{
    font-size: 0.68rem;
    color: {MUTED};
    text-transform: uppercase;
    letter-spacing: 0.1em;
    margin-bottom: 0.4rem;
  }}
  .stat-value {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 1.9rem;
    font-weight: 700;
    color: {TEXT};
    line-height: 1;
  }}
  .stat-sub {{
    font-size: 0.7rem;
    color: {MUTED};
    margin-top: 0.3rem;
  }}

  /* ── Leaderboard ── */
  .lb-row {{
    display: flex;
    align-items: center;
    gap: 0.9rem;
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 10px;
    padding: 0.85rem 1.1rem;
    margin-bottom: 0.6rem;
    transition: border-color 0.2s;
    cursor: default;
  }}
  .lb-row:hover {{ border-color: {POSTHOG_ORANGE}88; }}
  .lb-rank {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 1.5rem;
    font-weight: 800;
    color: {MUTED};
    min-width: 2rem;
    text-align: right;
  }}
  .lb-rank.top1 {{ color: #FFD700; }}
  .lb-rank.top2 {{ color: #C0C0C0; }}
  .lb-rank.top3 {{ color: #CD7F32; }}
  .lb-avatar {{
    width: 36px; height: 36px;
    border-radius: 50%;
    background: linear-gradient(135deg, {POSTHOG_ORANGE}66, {ACCENT_BLUE}66);
    display: flex; align-items: center; justify-content: center;
    font-size: 1rem; font-weight: 700; color: {TEXT};
    flex-shrink: 0;
  }}
  .lb-info {{ flex: 1; min-width: 0; }}
  .lb-name {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-weight: 600;
    font-size: 0.95rem;
    color: {TEXT};
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  }}
  .lb-tags {{
    display: flex; gap: 0.3rem; flex-wrap: wrap; margin-top: 0.25rem;
  }}
  .lb-tag {{
    font-size: 0.58rem;
    padding: 0.1rem 0.4rem;
    border-radius: 4px;
    background: {BORDER};
    color: {MUTED};
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }}
  .lb-tag.bug    {{ background: #7F1D1D44; color: #FCA5A5; }}
  .lb-tag.enterprise {{ background: #1E3A5F44; color: #93C5FD; }}
  .lb-tag.perf   {{ background: #1A1A2E44; color: #A78BFA; }}
  .lb-score-block {{ text-align: right; flex-shrink: 0; }}
  .lb-total {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 1.4rem;
    font-weight: 700;
    color: {POSTHOG_ORANGE};
  }}
  .lb-score-sub {{
    font-size: 0.64rem; color: {MUTED}; margin-top: 0.15rem;
  }}
  .lb-bar-wrap {{ width: 90px; }}
  .lb-bar-bg {{
    height: 4px; background: {BORDER}; border-radius: 2px; overflow: hidden;
  }}
  .lb-bar-fill {{
    height: 100%; background: {POSTHOG_ORANGE}; border-radius: 2px;
  }}

  /* ── Section headers ── */
  .section-label {{
    font-size: 0.68rem;
    color: {MUTED};
    text-transform: uppercase;
    letter-spacing: 0.12em;
    margin-bottom: 0.75rem;
    display: flex; align-items: center; gap: 0.5rem;
  }}
  .section-label::after {{
    content: ''; flex: 1; height: 1px; background: {BORDER};
  }}

  /* ── Chart panels ── */
  .chart-card {{
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 10px;
    padding: 1.1rem 1.2rem 0.6rem;
  }}
  .chart-title {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 0.85rem;
    font-weight: 600;
    color: {TEXT};
    margin-bottom: 0.75rem;
    letter-spacing: -0.01em;
  }}

  /* ── Detail panel ── */
  .detail-header {{
    display: flex; align-items: flex-start; gap: 1rem;
    margin-bottom: 1rem;
  }}
  .detail-avatar {{
    width: 54px; height: 54px; border-radius: 50%;
    background: linear-gradient(135deg, {POSTHOG_ORANGE}, {ACCENT_BLUE});
    display: flex; align-items: center; justify-content: center;
    font-size: 1.5rem; font-weight: 800; color: #fff;
    flex-shrink: 0;
  }}
  .detail-name {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 1.4rem; font-weight: 700; color: {TEXT};
    margin: 0;
  }}
  .detail-meta {{
    font-size: 0.7rem; color: {MUTED}; margin-top: 0.2rem;
  }}

  /* ── Score breakdown bars ── */
  .score-row {{
    display: flex; align-items: center; gap: 0.75rem;
    margin-bottom: 0.55rem;
  }}
  .score-label {{
    font-size: 0.7rem; color: {MUTED};
    text-transform: uppercase; letter-spacing: 0.08em;
    min-width: 100px;
  }}
  .score-bar-outer {{
    flex: 1; height: 8px; background: {BORDER}; border-radius: 4px;
    overflow: hidden;
  }}
  .score-bar-inner {{
    height: 100%; border-radius: 4px;
    transition: width 0.4s ease;
  }}
  .score-num {{
    font-family: 'Bricolage Grotesque', sans-serif;
    font-size: 0.85rem; font-weight: 600; color: {TEXT};
    min-width: 48px; text-align: right;
  }}

  /* ── PR table ── */
  table {{ width: 100%; border-collapse: collapse; }}
  th {{
    font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.1em;
    color: {MUTED}; padding: 0.4rem 0.6rem; border-bottom: 1px solid {BORDER};
    text-align: left;
  }}
  td {{
    font-size: 0.75rem; padding: 0.45rem 0.6rem;
    border-bottom: 1px solid {BORDER}22;
    color: {TEXT}cc;
  }}
  tr:last-child td {{ border-bottom: none; }}
  .pr-score {{ color: {POSTHOG_ORANGE}; font-weight: 600; }}
  .pr-label {{
    font-size: 0.58rem; padding: 0.1rem 0.35rem; border-radius: 3px;
    background: {BORDER}; color: {MUTED}; margin-right: 0.25rem;
    display: inline-block;
  }}

  /* ── Methodology accordion ── */
  .method-box {{
    background: {CARD_BG};
    border: 1px solid {BORDER};
    border-radius: 10px;
    padding: 1.1rem 1.3rem;
  }}
  .method-item {{
    display: flex; gap: 0.75rem; margin-bottom: 0.7rem; align-items: flex-start;
  }}
  .method-icon {{
    font-size: 1.1rem; flex-shrink: 0; margin-top: 0.05rem;
  }}
  .method-text {{ font-size: 0.76rem; color: {TEXT}cc; line-height: 1.6; }}
  .method-text strong {{ color: {TEXT}; font-weight: 500; }}

  /* Streamlit overrides */
  [data-testid="stSelectbox"] div[data-baseweb="select"] {{
    background: {CARD_BG} !important;
    border: 1px solid {BORDER} !important;
    border-radius: 8px !important;
  }}
  [data-testid="stSelectbox"] * {{ color: {TEXT} !important; font-family: 'DM Mono', monospace !important; }}
  [data-testid="stMarkdownContainer"] p {{ font-size: 0.82rem; }}

  /* Tab overrides */
  [data-testid="stTabs"] [role="tab"] {{
    font-family: 'DM Mono', monospace !important;
    font-size: 0.78rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: {MUTED} !important;
  }}
  [data-testid="stTabs"] [role="tab"][aria-selected="true"] {{
    color: {TEXT} !important;
    border-bottom: 2px solid {POSTHOG_ORANGE} !important;
  }}

  /* Metric delta override */
  [data-testid="stMetricDelta"] {{ font-size: 0.7rem !important; }}
</style>
""", unsafe_allow_html=True)

# ── Sample data (used when posthog_data.json is absent) ──────────────────────

SAMPLE_DATA = {
    "generated_at": "2025-02-27T12:00:00+00:00",
    "repo":         "PostHog/posthog",
    "days_back":    90,
    "total_prs":    847,
    "engineers": {
        "mariusandra": {
            "login": "mariusandra",
            "merged_prs": 68, "pr_score": 412.4, "review_score": 187.2,
            "approvals_given": 42, "changes_requested": 18, "reviews_given": 74,
            "labels_touched": ["feature", "frontend", "ux", "performance"],
            "total_additions": 14200, "total_deletions": 8700,
            "avg_response_hours": 3.2, "total_score": 599.6,
            "pr_details": [
                {"number": 19821, "title": "feat: new insight sidebar", "merged": "2024-12-10", "score": 22.4, "labels": ["feature", "ux"], "mult": 1.4, "size": 4.2, "vel_pen": 1.0},
                {"number": 19654, "title": "perf: reduce query re-renders", "merged": "2024-12-05", "score": 28.1, "labels": ["performance"], "mult": 1.8, "size": 3.8, "vel_pen": 0.9},
                {"number": 19433, "title": "fix: person modal crash", "merged": "2024-11-28", "score": 18.7, "labels": ["bug"], "mult": 2.0, "size": 2.1, "vel_pen": 1.0},
            ]
        },
        "paolodamico": {
            "login": "paolodamico",
            "merged_prs": 55, "pr_score": 367.8, "review_score": 203.5,
            "approvals_given": 51, "changes_requested": 22, "reviews_given": 88,
            "labels_touched": ["enterprise", "bug", "security"],
            "total_additions": 11400, "total_deletions": 6200,
            "avg_response_hours": 5.8, "total_score": 571.3,
            "pr_details": [
                {"number": 19711, "title": "enterprise: SAML SSO improvements", "merged": "2024-12-08", "score": 31.5, "labels": ["enterprise", "security"], "mult": 2.5, "size": 3.1, "vel_pen": 0.9},
                {"number": 19522, "title": "fix: billing edge cases", "merged": "2024-12-01", "score": 24.8, "labels": ["bug", "enterprise"], "mult": 2.5, "size": 2.8, "vel_pen": 0.9},
                {"number": 19301, "title": "feat: org-level insights", "merged": "2024-11-20", "score": 19.2, "labels": ["enterprise"], "mult": 2.5, "size": 1.9, "vel_pen": 0.75},
            ]
        },
        "timgl": {
            "login": "timgl",
            "merged_prs": 72, "pr_score": 389.1, "review_score": 141.6,
            "approvals_given": 28, "changes_requested": 31, "reviews_given": 66,
            "labels_touched": ["clickhouse", "performance", "bug"],
            "total_additions": 19800, "total_deletions": 11200,
            "avg_response_hours": 2.1, "total_score": 530.7,
            "pr_details": [
                {"number": 19890, "title": "clickhouse: optimize funnel query", "merged": "2024-12-12", "score": 34.2, "labels": ["clickhouse", "performance"], "mult": 2.0, "size": 4.9, "vel_pen": 1.0},
                {"number": 19700, "title": "fix: session recording storage bug", "merged": "2024-12-07", "score": 26.7, "labels": ["bug", "clickhouse"], "mult": 2.0, "size": 3.7, "vel_pen": 1.0},
                {"number": 19482, "title": "perf: materialized columns", "merged": "2024-11-30", "score": 29.8, "labels": ["clickhouse", "performance"], "mult": 2.0, "size": 4.1, "vel_pen": 1.0},
            ]
        },
        "EDsCODE": {
            "login": "EDsCODE",
            "merged_prs": 48, "pr_score": 295.6, "review_score": 198.4,
            "approvals_given": 46, "changes_requested": 27, "reviews_given": 91,
            "labels_touched": ["feature", "enterprise", "ux"],
            "total_additions": 9100, "total_deletions": 5300,
            "avg_response_hours": 4.4, "total_score": 494.0,
            "pr_details": [
                {"number": 19775, "title": "feat: group analytics v2", "merged": "2024-12-09", "score": 27.3, "labels": ["feature", "enterprise"], "mult": 2.5, "size": 2.8, "vel_pen": 0.9},
                {"number": 19551, "title": "ux: cohort builder redesign", "merged": "2024-12-02", "score": 18.9, "labels": ["ux", "feature"], "mult": 1.4, "size": 3.6, "vel_pen": 1.0},
                {"number": 19388, "title": "fix: filter by cohort regression", "merged": "2024-11-24", "score": 21.4, "labels": ["bug"], "mult": 2.0, "size": 2.9, "vel_pen": 0.9},
            ]
        },
        "Twixes": {
            "login": "Twixes",
            "merged_prs": 41, "pr_score": 278.3, "review_score": 162.7,
            "approvals_given": 35, "changes_requested": 24, "reviews_given": 71,
            "labels_touched": ["bug", "performance", "clickhouse"],
            "total_additions": 8600, "total_deletions": 4900,
            "avg_response_hours": 6.7, "total_score": 441.0,
            "pr_details": [
                {"number": 19832, "title": "perf: HogQL query compilation", "merged": "2024-12-11", "score": 29.1, "labels": ["performance", "clickhouse"], "mult": 2.0, "size": 4.0, "vel_pen": 1.0},
                {"number": 19688, "title": "fix: data loss in migration", "merged": "2024-12-06", "score": 36.4, "labels": ["bug", "data loss"], "mult": 2.5, "size": 4.3, "vel_pen": 0.9},
                {"number": 19501, "title": "refactor: event ingestion pipeline", "merged": "2024-12-01", "score": 22.8, "labels": ["performance"], "mult": 1.8, "size": 3.5, "vel_pen": 0.9},
            ]
        },
        "zach-posthog": {
            "login": "zach-posthog",
            "merged_prs": 39, "pr_score": 251.4, "review_score": 134.6,
            "approvals_given": 29, "changes_requested": 19, "reviews_given": 58,
            "labels_touched": ["feature", "ux", "bug"],
            "total_additions": 7200, "total_deletions": 3800,
            "avg_response_hours": 8.3, "total_score": 386.0,
            "pr_details": []
        },
        "robbie-c": {
            "login": "robbie-c",
            "merged_prs": 34, "pr_score": 223.7, "review_score": 149.2,
            "approvals_given": 33, "changes_requested": 21, "reviews_given": 63,
            "labels_touched": ["enterprise", "bug"],
            "total_additions": 6500, "total_deletions": 3200,
            "avg_response_hours": 7.1, "total_score": 372.9,
            "pr_details": []
        },
    }
}

# ── Data loading ──────────────────────────────────────────────────────────────

@st.cache_data(show_spinner=False)
def load_data() -> dict:
    path = Path("posthog_data.json")
    if path.exists():
        with open(path) as f:
            raw = json.load(f)
        return raw
    return SAMPLE_DATA


def engineers_df(data: dict) -> pd.DataFrame:
    rows = []
    for eng in data["engineers"].values():
        rows.append({
            "login":             eng["login"],
            "total_score":       eng["total_score"],
            "pr_score":          eng["pr_score"],
            "review_score":      eng["review_score"],
            "merged_prs":        eng["merged_prs"],
            "reviews_given":     eng["reviews_given"],
            "approvals_given":   eng["approvals_given"],
            "changes_requested": eng["changes_requested"],
            "total_additions":   eng["total_additions"],
            "total_deletions":   eng["total_deletions"],
            "avg_response_hours": eng.get("avg_response_hours"),
            "labels_touched":    eng.get("labels_touched", []),
        })
    df = pd.DataFrame(rows).sort_values("total_score", ascending=False).reset_index(drop=True)
    df.index += 1
    return df


def tag_color(label: str) -> str:
    l = label.lower()
    if "bug" in l:      return "bug"
    if "enterprise" in l: return "enterprise"
    if "perf" in l:     return "perf"
    return ""


# ── UI helpers ────────────────────────────────────────────────────────────────

def score_bar(label: str, value: float, max_val: float, color: str) -> str:
    pct = min(value / max_val * 100, 100) if max_val else 0
    return f"""
    <div class="score-row">
      <span class="score-label">{label}</span>
      <div class="score-bar-outer">
        <div class="score-bar-inner" style="width:{pct:.1f}%;background:{color}"></div>
      </div>
      <span class="score-num">{value:.1f}</span>
    </div>"""


def rank_css(i: int) -> str:
    if i == 1: return "top1"
    if i == 2: return "top2"
    if i == 3: return "top3"
    return ""


def leaderboard_row(row: pd.Series, rank: int, max_score: float) -> str:
    pct = int(row["total_score"] / max_score * 100)
    initials = "".join(p[0].upper() for p in row["login"].replace("-", " ").split()[:2])
    labels = row["labels_touched"][:3]
    tags_html = "".join(
        f'<span class="lb-tag {tag_color(l)}">{l}</span>' for l in labels
    )
    resp = f"{row['avg_response_hours']:.1f}h" if row["avg_response_hours"] else "—"
    return f"""
    <div class="lb-row">
      <span class="lb-rank {rank_css(rank)}">{rank}</span>
      <div class="lb-avatar">{initials}</div>
      <div class="lb-info">
        <div class="lb-name">{row['login']}</div>
        <div class="lb-tags">{tags_html}</div>
      </div>
      <div class="lb-score-block">
        <div class="lb-total">{row['total_score']:.0f}</div>
        <div class="lb-score-sub">
          Pull Request Score: {row['pr_score']:.0f} · Review Score: {row['review_score']:.0f}
        </div>
        <div class="lb-bar-wrap">
          <div class="lb-bar-bg">
            <div class="lb-bar-fill" style="width:{pct}%"></div>
          </div>
        </div>
      </div>
    </div>"""


# ── Radar helper functions (module-level to avoid re-definition on tab switch) ─

def normalize(series) -> list:
    mx = series.max()
    return (series / mx * 100).tolist() if mx else [0] * len(series)


def vel_score(h) -> float:
    if h is None: return 50.0
    if h <= 4:    return 100.0
    if h <= 24:   return 75.0
    if h <= 72:   return 50.0
    return 25.0


# ── Main app ──────────────────────────────────────────────────────────────────

def main():
    data = load_data()
    df   = engineers_df(data)

    is_sample = not Path("posthog_data.json").exists()

    # ── Header ───────────────────────────────────────────────────────────────
    st.markdown(f"""
    <div class="ph-header">
      <div class="ph-logo">🦔</div>
      <div>
        <p class="ph-title">
          PostHog Engineer Impact
          <span class="ph-badge">{'SAMPLE DATA' if is_sample else 'LIVE'}</span>
        </p>
        <p class="ph-subtitle">
          {data['days_back']}-day window · {data['total_prs']} merged PRs ·
          {len(df)} contributors · Last fetched {data['generated_at'][:10]}
        </p>
      </div>
    </div>
    <div class="divider"></div>
    """, unsafe_allow_html=True)

    if is_sample:
        st.info(
            "**Running on built-in sample data.**  "
            "To use real PostHog data: run `fetch_posthog_data.py` with a GitHub token, "
            "then place `posthog_data.json` alongside this file.",
            icon="ℹ️"
        )

    # ── KPI strip ────────────────────────────────────────────────────────────
    top5    = df.head(5)
    total_prs_top5 = int(top5["merged_prs"].sum())
    total_rev_top5 = int(top5["reviews_given"].sum())
    avg_resp = df[df["avg_response_hours"].notna()]["avg_response_hours"].mean()

    st.markdown(f"""
    <div class="stat-grid">
      <div class="stat-card">
        <div class="stat-label">Top Scorer</div>
        <div class="stat-value">{df.iloc[0]['login']}</div>
        <div class="stat-sub">{df.iloc[0]['total_score']:.0f} impact points</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">PRs (top 5)</div>
        <div class="stat-value">{total_prs_top5}</div>
        <div class="stat-sub">merged last {data['days_back']}d</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Reviews (top 5)</div>
        <div class="stat-value">{total_rev_top5}</div>
        <div class="stat-sub">approvals + changes requested</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Average Review Speed</div>
        <div class="stat-value">{avg_resp:.1f}h</div>
        <div class="stat-sub">first substantive review</div>
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Main tabs ─────────────────────────────────────────────────────────────
    tab_charts, tab_lb, tab_detail = st.tabs([
        "📊  Analytics", "🏆  Leaderboard", "🔍  Engineer Detail"
    ])

    # ══ TAB 1 — Leaderboard ══════════════════════════════════════════════════
    with tab_lb:
        col_lb, col_mini = st.columns([3, 2], gap="large")

        with col_lb:
            st.markdown('<div class="section-label">Top Engineers by Impact Score</div>', unsafe_allow_html=True)
            max_score = float(df["total_score"].max())

            html_rows = ""
            for rank, (_, row) in enumerate(df.head(10).iterrows(), 1):
                html_rows += leaderboard_row(row, rank, max_score)
            st.markdown(html_rows, unsafe_allow_html=True)

        with col_mini:
            st.markdown('<div class="section-label">Score Composition — Top 5</div>', unsafe_allow_html=True)

            fig_stacked = go.Figure()
            top5_login = top5["login"].tolist()
            fig_stacked.add_trace(go.Bar(
                name="Pull Request Impact Score",
                x=top5_login,
                y=top5["pr_score"].tolist(),
                marker_color=POSTHOG_ORANGE,
                marker_line_width=0,
            ))
            fig_stacked.add_trace(go.Bar(
                name="Review Score",
                x=top5_login,
                y=top5["review_score"].tolist(),
                marker_color=ACCENT_BLUE,
                marker_line_width=0,
            ))
            fig_stacked.update_layout(
                **{
                    **PLOTLY_TEMPLATE["layout"],
                    "legend": dict(orientation="h", y=1.1, x=0),
                },
                barmode="stack",
                height=320,
            )
            st.plotly_chart(fig_stacked, use_container_width=True, config={"displayModeBar": False})

            st.markdown('<div class="section-label" style="margin-top:1rem">Review Velocity (average hours to first review)</div>', unsafe_allow_html=True)
            df_resp = df[df["avg_response_hours"].notna()].head(10)
            colors = [ACCENT_GREEN if h <= 4 else ACCENT_AMBER if h <= 24 else POSTHOG_ORANGE
                      for h in df_resp["avg_response_hours"]]
            fig_vel = go.Figure(go.Bar(
                x=df_resp["login"].tolist(),
                y=df_resp["avg_response_hours"].tolist(),
                marker_color=colors,
                marker_line_width=0,
                text=[f"{h:.1f}h" for h in df_resp["avg_response_hours"]],
                textposition="outside",
                textfont=dict(size=9, color=TEXT),
            ))
            fig_vel.update_layout(
                **{**PLOTLY_TEMPLATE["layout"]},
                height=360,
                yaxis_title="Hours",
                shapes=[dict(type="line", x0=-0.5, x1=len(df_resp)-0.5,
                             y0=24, y1=24, line=dict(color=hex_to_rgba(POSTHOG_ORANGE, 0.53), dash="dot", width=1))],
                annotations=[dict(x=len(df_resp)-1, y=25, text="24h target",
                                  showarrow=False, font=dict(size=9, color=MUTED))]
            )
            st.plotly_chart(fig_vel, use_container_width=True, config={"displayModeBar": False})

    # ══ TAB 2 — Analytics ════════════════════════════════════════════════════
    with tab_charts:

        # ── Methodology section ───────────────────────────────────────────────
        st.markdown('<div class="section-label">How Impact Is Calculated</div>', unsafe_allow_html=True)
        st.markdown(f"""
        <div class="method-box">
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:0.75rem 2rem">
            <div class="method-item">
              <div class="method-icon">📐</div>
              <div class="method-text">
                <strong>Base Pull Request Score</strong> — Every merged PR starts with a base of <strong>3.0 points</strong>.
                A non-linear size bonus adds up to <strong>8.0 points</strong> based on net lines changed and
                files touched, capped to prevent mega-PRs from dominating the board.
              </div>
            </div>
            <div class="method-item">
              <div class="method-icon">🏷</div>
              <div class="method-text">
                <strong>Label Multipliers</strong> — PRs are multiplied by their highest-value label.
                <em>enterprise</em> &amp; <em>security</em>: ×2.5 · <em>bug</em>: ×2.0 ·
                <em>performance</em>: ×1.8 · <em>feature</em>: ×1.4 · <em>automerge</em>: ×0.7.
              </div>
            </div>
            <div class="method-item">
              <div class="method-icon">👀</div>
              <div class="method-text">
                <strong>Review Score</strong> — High-cognitive-load work that unblocks peers.
                <em>Changes Requested</em>: <strong>6× multiplier</strong> ·
                <em>Approved</em>: <strong>4× multiplier</strong> ·
                Comment-only: partial credit by body length. Duplicate reviews de-duped.
              </div>
            </div>
            <div class="method-item">
              <div class="method-icon">⚡</div>
              <div class="method-text">
                <strong>Velocity Penalty</strong> — Slow reviews create bottlenecks.
                First review &gt;72h: ×0.6 penalty · ≤72h: ×0.75 · ≤24h: ×0.9 · ≤4h: no penalty.
              </div>
            </div>
            <div class="method-item">
              <div class="method-icon">🤖</div>
              <div class="method-text">
                <strong>Bot Filtering</strong> — All activity from <em>dependabot</em>, <em>renovate</em>,
                <em>github-actions</em>, <em>posthog-bot</em>, etc. is excluded. Self-reviews are also removed.
              </div>
            </div>
            <div class="method-item">
              <div class="method-icon">📖</div>
              <div class="method-text">
                <strong>Why not LOC?</strong> — A 3-line critical bug fix outscores a 500-line auto-generated
                migration. Aligned with <strong>DORA, SPACE &amp; DX Core 4</strong>: outcomes over volume.
              </div>
            </div>
          </div>
          <div style="margin-top:1rem;padding:0.75rem 1rem;
               background:{DARK_BG};border-radius:6px;font-size:0.7rem;color:{MUTED}">
            <strong style="color:{TEXT}">Formulas:</strong> &nbsp;
            <code style="color:{POSTHOG_ORANGE}">PR Impact Score = (3.0 + Size Bonus) × Label Multiplier × Velocity Penalty</code>
            <br style="margin:0.3rem 0">
            <code style="color:{ACCENT_BLUE}">Review Impact Score += Review Points × Label Multiplier of Reviewed PR</code>
            <br style="margin:0.3rem 0">
            <code style="color:{ACCENT_GREEN}">Total Impact Score = PR Impact Score + Review Impact Score</code>
          </div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown('<div class="divider" style="margin:1.25rem 0"></div>', unsafe_allow_html=True)

        # ── Charts ────────────────────────────────────────────────────────────
        c1, c2 = st.columns([1, 2], gap="large")

        with c1:
            st.markdown('<div class="section-label">PRs Merged vs. Reviews Given</div>', unsafe_allow_html=True)
            df_plot = df.head(15).copy()
            df_plot["review_ratio"] = (df_plot["review_score"] / df_plot["total_score"] * 100).round(1)
            fig_scatter = px.scatter(
                df_plot,
                x="merged_prs", y="reviews_given",
                size="total_score",
                color="review_ratio",
                color_continuous_scale=[[0, POSTHOG_ORANGE], [0.5, ACCENT_AMBER], [1, ACCENT_BLUE]],
                hover_name="login",
                hover_data={
                    "merged_prs":    False,   # shown via hovertemplate instead
                    "reviews_given": False,
                    "total_score":   True,
                    "review_ratio":  True,
                    "pr_score":      True,
                    "review_score":  True,
                },
                labels={"merged_prs": "Merged PRs", "reviews_given": "Reviews Given",
                        "review_ratio": "Review Score Share %"},
                size_max=42,
            )
            fig_scatter.update_layout(
                **{**PLOTLY_TEMPLATE["layout"]},
                height=360,
                coloraxis_colorbar=dict(
                    thickness=10, len=0.7, tickfont=dict(size=9, color=TEXT),
                    title=dict(text="Rev %", font=dict(size=9, color=MUTED))
                )
            )
            fig_scatter.update_traces(
                marker_line_width=0,
                hovertemplate=(
                    "<b>%{hovertext}</b><br><br>"
                    "PRs merged:          <b>%{x}</b><br>"
                    "Reviews given:       <b>%{y}</b><br>"
                    "──────────────────<br>"
                    "Total impact score:  <b>%{customdata[0]:.0f} points</b><br>"
                    "  ↳ from Pull Requests:  <b>%{customdata[2]:.0f} points</b><br>"
                    "  ↳ from Reviews:        <b>%{customdata[3]:.0f} points</b><br>"
                    "Review share:        <b>%{customdata[1]:.1f}%</b> of total score"
                    "<extra></extra>"
                ),
            )
            st.plotly_chart(fig_scatter, use_container_width=True, config={"displayModeBar": False})

        with c2:
            st.markdown('<div class="section-label">Impact Score Radar — Top 5</div>', unsafe_allow_html=True)

            categories = ["Pull Request Score", "Review Score", "Pull Requests Merged", "Reviews Given", "Review Velocity"]

            top5_df = df.head(5)
            ps  = normalize(top5_df["pr_score"])
            rs  = normalize(top5_df["review_score"])
            pm  = normalize(top5_df["merged_prs"])
            rg  = normalize(top5_df["reviews_given"])
            vs  = [vel_score(h) for h in top5_df["avg_response_hours"]]

            fig_radar = go.Figure()
            palette   = [POSTHOG_ORANGE, ACCENT_BLUE, ACCENT_GREEN, ACCENT_AMBER, "#A78BFA"]

            for i, (_, row) in enumerate(top5_df.iterrows()):
                vals = [ps[i], rs[i], pm[i], rg[i], vs[i]]
                vals_closed = vals + [vals[0]]
                cats_closed = categories + [categories[0]]
                fig_radar.add_trace(go.Scatterpolar(
                    r=vals_closed, theta=cats_closed,
                    fill="toself", name=row["login"],
                    line_color=palette[i],
                    fillcolor=hex_to_rgba(palette[i], 0.13),
                    line_width=1.5,
                ))

            fig_radar.update_layout(
                **{
                    **PLOTLY_TEMPLATE["layout"],
                    "legend": dict(
                        orientation="v",
                        x=1.05,
                        y=0.5,
                        xanchor="left",
                        yanchor="middle",
                        font=dict(size=11, color=TEXT),
                        bgcolor="rgba(0,0,0,0)",
                        bordercolor=BORDER,
                    ),
                    "margin": dict(l=16, r=160, t=32, b=16),
                },
                polar=dict(
                    domain=dict(x=[0, 0.78]),
                    bgcolor="rgba(0,0,0,0)",
                    radialaxis=dict(visible=True, range=[0, 100], gridcolor=BORDER,
                                   tickfont=dict(size=8, color=MUTED), tickvals=[25,50,75,100]),
                    angularaxis=dict(gridcolor=BORDER, tickfont=dict(size=10, color=TEXT)),
                ),
                height=460,
            )
            st.plotly_chart(fig_radar, use_container_width=True, config={"displayModeBar": False})

        # ── Code volume heatmap ────────────────────────────────────────────
        st.markdown('<div class="section-label" style="margin-top:0.5rem">Code Contribution Profile</div>', unsafe_allow_html=True)

        df_vol = df.head(10).copy()
        df_vol["net_lines"]  = df_vol["total_additions"] - df_vol["total_deletions"]
        df_vol["del_ratio"]  = (df_vol["total_deletions"] /
                                 (df_vol["total_additions"] + 1) * 100).round(1)

        fig_vol = go.Figure()
        fig_vol.add_trace(go.Bar(
            name="Additions",
            x=df_vol["login"].tolist(),
            y=df_vol["total_additions"].tolist(),
            marker_color=hex_to_rgba(ACCENT_GREEN, 0.8),
            marker_line_width=0,
        ))
        fig_vol.add_trace(go.Bar(
            name="Deletions",
            x=df_vol["login"].tolist(),
            y=[-v for v in df_vol["total_deletions"].tolist()],
            marker_color=hex_to_rgba(POSTHOG_ORANGE, 0.8),
            marker_line_width=0,
        ))
        fig_vol.update_layout(
            **{
                **PLOTLY_TEMPLATE["layout"],
                "legend": dict(orientation="h", y=1.08),
                "yaxis": {
                    **PLOTLY_TEMPLATE["layout"]["yaxis"],
                    "tickformat": ",",
                    "zeroline": True,
                    "zerolinecolor": BORDER,
                },
            },
            barmode="relative",
            height=280,
            yaxis_title="Lines",
        )
        st.plotly_chart(fig_vol, use_container_width=True, config={"displayModeBar": False})

    # ══ TAB 3 — Engineer Detail ═══════════════════════════════════════════
    with tab_detail:
        st.markdown('<div class="section-label">Deep-dive into any contributor</div>', unsafe_allow_html=True)

        selected_login = st.selectbox(
            "Select engineer",
            options=df["login"].tolist(),
            index=0,
            label_visibility="collapsed",
        )

        eng_raw = data["engineers"].get(selected_login, {})
        eng_row = df[df["login"] == selected_login].iloc[0]

        # Header card
        initials = "".join(p[0].upper() for p in selected_login.replace("-", " ").split()[:2])
        rank_n   = df[df["login"] == selected_login].index[0]
        resp_txt = f"{eng_row['avg_response_hours']:.1f}h average review response time" if eng_row["avg_response_hours"] else "no response data"
        pct_rev  = eng_row["review_score"] / eng_row["total_score"] * 100 if eng_row["total_score"] else 0

        st.markdown(f"""
        <div class="chart-card">
          <div class="detail-header">
            <div class="detail-avatar">{initials}</div>
            <div>
              <p class="detail-name">@{selected_login}</p>
              <p class="detail-meta">
                Rank #{rank_n} &nbsp;·&nbsp; {eng_row['merged_prs']} merged PRs &nbsp;·&nbsp;
                {eng_row['reviews_given']} reviews &nbsp;·&nbsp; {resp_txt}
              </p>
            </div>
          </div>
          <div style="margin-top:0.75rem">
            {score_bar("Pull Request Impact", eng_row["pr_score"], float(df["pr_score"].max()), POSTHOG_ORANGE)}
            {score_bar("Review Impact", eng_row["review_score"], float(df["review_score"].max()), ACCENT_BLUE)}
            {score_bar("Total Score", eng_row["total_score"], float(df["total_score"].max()), ACCENT_GREEN)}
          </div>
          <div style="margin-top:0.9rem;display:flex;gap:1.5rem;font-size:0.72rem;color:{MUTED}">
            <span>✅ <b style="color:{TEXT}">{eng_row['approvals_given']}</b> approvals given</span>
            <span>🔴 <b style="color:{TEXT}">{eng_row['changes_requested']}</b> changes requested</span>
            <span>📝 <b style="color:{TEXT}">{int(eng_row['total_additions']):,}</b> additions</span>
            <span>🗑 <b style="color:{TEXT}">{int(eng_row['total_deletions']):,}</b> deletions</span>
            <span>🏷 <b style="color:{TEXT}">{pct_rev:.0f}%</b> score from reviews</span>
          </div>
        </div>
        """, unsafe_allow_html=True)

        # PR details table
        pr_details = eng_raw.get("pr_details", [])
        if pr_details:
            st.markdown(f'<div class="section-label" style="margin-top:1rem">Recent High-Impact PRs</div>', unsafe_allow_html=True)
            rows_html = ""
            for pr in sorted(pr_details, key=lambda x: x["score"], reverse=True):
                label_pills = "".join(f'<span class="pr-label">{l}</span>' for l in pr["labels"])
                rows_html += f"""
                <tr>
                  <td><a href="https://github.com/PostHog/posthog/pull/{pr['number']}"
                         style="color:{ACCENT_BLUE};text-decoration:none">#{pr['number']}</a></td>
                  <td>{pr['title'][:70]}{'…' if len(pr['title'])>70 else ''}</td>
                  <td>{pr['merged']}</td>
                  <td>{label_pills}</td>
                  <td>×{pr['mult']}</td>
                  <td class="pr-score">{pr['score']:.1f}</td>
                </tr>"""

            st.markdown(f"""
            <div class="chart-card" style="overflow-x:auto">
              <table>
                <thead>
                  <tr>
                    <th>#</th><th>Title</th><th>Merged</th>
                    <th>Labels</th><th>Label Multiplier</th><th>Impact Score</th>
                  </tr>
                </thead>
                <tbody>{rows_html}</tbody>
              </table>
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f'<p style="color:{MUTED};font-size:0.78rem">No PR detail data available for this engineer.</p>', unsafe_allow_html=True)

    # ── Footer ────────────────────────────────────────────────────────────────
    st.markdown(f"""
    <div style="margin-top:3rem;border-top:1px solid {BORDER};padding-top:1rem;
         display:flex;justify-content:space-between;align-items:center">
      <span style="font-size:0.65rem;color:{MUTED}">
        PostHog Engineer Impact Dashboard &nbsp;·&nbsp; Data window: {data['days_back']}d
        &nbsp;·&nbsp; {data['total_prs']} PRs analysed
      </span>
      <span style="font-size:0.65rem;color:{MUTED}">
        Scoring: DORA + SPACE aligned &nbsp;·&nbsp; Built with Streamlit + Plotly
      </span>
    </div>
    """, unsafe_allow_html=True)


if __name__ == "__main__":
    main()